### ISSUE TITLE
Overflow Exception with NetRandomSeed.cs

### ISSUE THREAD

**Issue by captkirk88** [lidgren/lidgren-network-gen3#20]
The code is
```csharp
		[CLSCompliant(false)]
		public static ulong GetUInt64()
		{
#if !__ANDROID__ && !IOS && !UNITY_WEBPLAYER && !UNITY_ANDROID && !UNITY_IPHONE
			ulong seed = (ulong)System.Diagnostics.Stopwatch.GetTimestamp();
			seed ^= (ulong)Environment.WorkingSet;
			ulong s2 = (ulong)Interlocked.Increment(ref m_seedIncrement);
			s2 |= (((ulong)Guid.NewGuid().GetHashCode()) << 32);
			seed ^= s2;
#else
			ulong seed = (ulong)Environment.TickCount;
			seed |= (((ulong)(new object().GetHashCode())) << 32);
			ulong s2 = (ulong)Guid.NewGuid().GetHashCode();
			s2 |= (((ulong)Interlocked.Increment(ref m_seedIncrement)) << 32);
			seed ^= s2;
#endif
			return seed;
		}
```
I use the compilation preprocessor symbols DEBUG;TRACE only.  I use the PlatformWin.  The exception is:
```
System.TypeInitializationException: The type initializer for 'Lidgren.Network.MWCRandom' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Lidgren.Network.NetRandom' threw an exception. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Lidgren.Network.NetRandomSeed.GetUInt64() in NetRandomSeed.cs:line 34
   at Lidgren.Network.NetRandomSeed.GetUInt32() in NetRandomSeed.cs:line 19
   at Lidgren.Network.NetRandom..ctor() in NetRandom.cs:line 24
   at Lidgren.Network.MWCRandom..ctor() in NetRandom.Implementations.cs:line 21
   at Lidgren.Network.NetRandom..cctor() in NetRandom.cs:line 15
   --- End of inner exception stack trace ---
   at Lidgren.Network.NetRandom..ctor()
   at Lidgren.Network.MWCRandom..ctor() in NetRandom.Implementations.cs:line 21
   at Lidgren.Network.MWCRandom..cctor() in NetRandom.Implementations.cs:line 14
   --- End of inner exception stack trace ---
   at Lidgren.Network.NetPeer.InitializeNetwork() in NetPeer.Internal.cs:line 170
   at Lidgren.Network.NetPeer.Start() in NetPeer.cs:line 146
```
Turning off the "Generate overflow checks" causes the unit test to hang indefinitely even in debug mode.

Any help fixing this would be greatly appreciated.  It has been a show stopper with the network side of the house.

**Comment by captkirk88** [comment]
Did a clean delete of my version and updated.  Now I have the latest NetRandom code.  For some reason the files that were auto-formatted when I was looking at them, NetRandomSeed being one, did not update when I pulled for a new version off git.  Closing this issue.
