### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by ItalyToast** [lidgren/lidgren-network-gen3#3]
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Lidgren.Network.NetPeer.Heartbeat() in Lidgren.Network\NetPeer.Internal.cs:line 342
   at Lidgren.Network.NetPeer.NetworkLoop() in Lidgren.Network\NetPeer.Internal.cs:line 227

NetPeer.m_handshakes appear to not work correctly when NetIncomingMessageType.ConnectionApproval is enabled.

I'll continue to try to find the problem.

**Comment by lidgren** [comment]
commit 4b7b53b36da1b37259bce3a734921b0d54e741a7 should solve the problem
